[build]
builder = "nixpacks"
buildCommand = "composer install && npm ci && npm run build && php artisan optimize && php artisan config:cache && php artisan route:cache && php artisan view:cache"

[deploy]
startCommand = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"